[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "spectrograph-etc"
version = "0.1.0"
description = "Exposure-time calculator for the MLO spectrograph"
readme = "README.md"
authors = [
    {name = "Caden Gobat", email = "cgobat@sdsu.edu"},
    {name = "Ian Beard", email = "ibeard5884@sdsu.edu"},
    {name = "Madi Catalano", email = "madicatalano425@berkeley.edu"},
]
requires-python = ">=3.10"
dependencies = [
    "astropy",
    "matplotlib",
    "numpy",
    "shared-data",
    "spectrograph-sim",
]

[project.scripts]
spectrograph-etc = "etc.gui:run"

[tool.setuptools]
packages = ["etc"]
package-dir = {etc = "app"}
